fieldLayouts:
  0c4490e9-c0dd-403d-94cd-cc06787ca234:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: af15b289-0af8-48cf-a4bd-25d32d687140
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: a5b507ee-e4ae-49a3-ae4a-db0fcfafd5d9
        userCondition: null
fs: documents
handle: documents
name: Dokumente
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
